const urls = [
   "./groups/A_4.group",
   "./groups/A_5.group",
   "./groups/D_10.group",
   "./groups/D_4 x Z_2.group",
   "./groups/D_4.group",
   "./groups/D_5.group",
   "./groups/D_6.group",
   "./groups/D_7.group",
   "./groups/D_8.group",
   "./groups/D_9.group",
   "./groups/Fr_20.group",
   "./groups/G_4,4.group",
   "./groups/Modular_16.group",
   "./groups/Q_4 x Z_2.group",
   "./groups/Q_4.group",
   "./groups/Q_8.group",
   "./groups/Quasihedral_16.group",
   "./groups/S_3 x Z_3.group",
   "./groups/S_3 x Z_4.group",
   "./groups/S_3.group",
   "./groups/S_4.group",
   "./groups/Trivial.group",
   "./groups/Twenty-one.group",
   "./groups/Unnamed1_16.group",
   "./groups/Unnamed2_16.group",
   "./groups/V_4.group",
   "./groups/Z_10.group",
   "./groups/Z_11.group",
   "./groups/Z_12.group",
   "./groups/Z_13.group",
   "./groups/Z_14.group",
   "./groups/Z_15.group",
   "./groups/Z_16.group",
   "./groups/Z_17.group",
   "./groups/Z_18.group",
   "./groups/Z_19.group",
   "./groups/Z_2 x Z_10.group",
   "./groups/Z_2 x Z_2 x Z_2 x Z_2.group",
   "./groups/Z_2 x Z_2 x Z_2 x Z_3.group",
   "./groups/Z_2 x Z_2 x Z_2.group",
   "./groups/Z_2 x Z_3 x Z_3 x Z_4.group",
   "./groups/Z_2 x Z_4 x Z_2.group",
   "./groups/Z_2 x Z_4.group",
   "./groups/Z_2 x Z_6.group",
   "./groups/Z_2 x Z_8.group",
   "./groups/Z_2.group",
   "./groups/Z_20.group",
   "./groups/Z_3 sdp Z_4.group",
   "./groups/Z_3 x Z_3 sdp Z_2.group",
   "./groups/Z_3 x Z_3.group",
   "./groups/Z_3 x Z_6.group",
   "./groups/Z_3.group",
   "./groups/Z_4 sdp Z_5.group",
   "./groups/Z_4 x Z_4.group",
   "./groups/Z_4.group",
   "./groups/Z_5.group",
   "./groups/Z_6.group",
   "./groups/Z_7.group",
   "./groups/Z_8.group",
   "./groups/Z_9.group",
/*
   "./groups/168.group",
   "./groups/Tesseract.group",
 */
];
